### PR TITLE
add aliases to document methods

### LINKED ISSUE #186: Use aliases to make doc easier to navigate
Since most things in CmdStanR are methods of R6 objects and not standalone functions, finding their doc is not the same as for typical R functions. We could use the `@aliases` tag in roxygen to make so that, e.g., `?draws` could be used instead of having to go `CmdStanMCMC` and click on the link to the draws method. Same for other methods. 

I can make a PR for this.

### PR DESCRIPTION
**Pull request by jgabry**
closes #186

#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Adds aliases to make it easier to find doc pages for methods (at least for the ones that have their own doc pages). For example, 

```r
?draws         # shortcut as ?"fit-method-draws"
?variational   # shortcut for ?"model-method-variational"
```

etcetera.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
**Columbia University**

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by bbbales2** [comment]
Does `sampling_info` need docs? Maybe not since it has no arguments and is pretty harmless to call, but it seems like it could be doc'ed pretty easily.

lp and lp_approx (variational only) probably deserve docs regarding normalizing constants, and what kind of approximation lp_approx is (or at least where next to look for information).

Are the `clone` and `initialize` functions things that people would ever use? Or are those internal functions or whatever?

**Comment by rok-cesnovar** [comment]
> Are the `clone` and `initialize` functions things that people would ever use? Or are those internal functions or whatever?

I believe these are part of all R6 classes to init or copy an R6 object.

**Comment by bbbales2** [comment]
Cool. I think it's fine if they're not doc'd if there's no use case for them (outside of whatever R is doing automatically in the background)

**Comment by jgabry** [comment]
Thanks. I just added a doc page for the `lp()` and `lp_approx()` methods. But I'm not sure where the best place to link to for info on the approximate lp for variational. The Stan manual's section on variational inference maybe? Also just realized I forgot to add info about normalizing constants. I'll add a link to the manual section about that after a call I have to take now.

**Comment by bbbales2** [comment]
> But I'm not sure where the best place to link to for info on the approximate lp for variational

Hmm, there should be a definition somewhere for this that isn't a research paper. I would have guess here would be the best chance for it: https://mc-stan.org/docs/2_23/reference-manual/vi-algorithms-chapter.html, but it's not there.

I'm not sure what this is exactly. Maybe @avehtari ?

**Comment by jgabry** [comment]
Ok I linked to the discussion on normalizing constants in the reference manual. Should we wait to add something about the variational approximation or go ahead and merge and add that later?

**Comment by jgabry** [comment]
Yeah you're right, let's wait.

**Comment by avehtari** [comment]
> Hmm, there should be a definition somewhere for this that isn't a research paper. I would have guess here would be the best chance for it: https://mc-stan.org/docs/2_23/reference-manual/vi-algorithms-chapter.html, but it's not there.
> 
> I'm not sure what this is exactly. Maybe @avehtari ?

The research paper would "Yes, but did it work?". If the reference manual doesn't say anything about it, we (I?) should write it there.

**Comment by bbbales2** [comment]
> we (I?) should write it there

Is this the basic story:

lp is the log density with the Jacobian adjustment on the unconstrained space
lp_approx is a variational approximation of lp on the unconstrained space

lp/lp_approx are exposed so that someone can do the PSIS checks/corrections documented in the "Yes, but does it work paper?"

----

If this is the case, then I think what needs to go in the ?lp/lp_approx docs is just enough to get people to the manual and some information that these lps are not going to be the same thing as just evaluating the model log density in the constrained space (cause the Jacobian adjustment).

And then the manual could be longer to give information on how the PSIS stuff works. We've made the manual language neutral, so whatever gets written there should be too. I think it would still be fine to link to the loo package (cause we're not actually encouraging people to re-implement this all themselves).

**Comment by avehtari** [comment]
> lp is the log density with the Jacobian adjustment on the unconstrained space
> lp_approx is a variational approximation of lp on the unconstrained space
>
> lp/lp_approx are exposed so that someone can do the PSIS checks/corrections documented in the "Yes, but does it work paper?"

Yes.

**Comment by bbbales2** [comment]
Cool thanks. Always scared I'm screwing these things up.

@jgabry The clarification for `lp` should have normalization constants + the Jacobian.

Maybe the line is, "lp is the unnormalized log density on Stan's [unconstrained space](https://mc-stan.org/docs/2_23/reference-manual/variable-transforms-chapter.html). This will in general be different than the unnormalized model log density evaluated at a posterior sample (which is on the constrained space). `lp` is intended to diagnose sampling efficiency and evaluate approximations."

"lp_approx is the log density of the variational approximation to lp (also on the unconstrained space). It is exposed in the `variational` method for performing the checks described in [cite "Yes, but does it work?] and implemented in the loo package."

I guess this is the loo function: https://mc-stan.org/loo/reference/psis.html . Is there a way to link to other stuff?

I guess if we can just point people in R-land to the loo package that is convenient. Though then we have sort of a documentation dependency on loo. That is easier that writing something in the manual (and faster), though cmdstanpy will have to document this somehow.

I don't know if that's clear or not. The goal is to put a simple blurb in the docs so people know enough about it to not get themselves in trouble.

**Comment by avehtari** [comment]
ArviZ has the support for Python

**Comment by bbbales2** [comment]
Oh indeed it does: https://arviz-devs.github.io/arviz/generated/arviz.psislw.html#arviz.psislw

Well then we circumvent the manual altogether. That's easy.

**Comment by avehtari** [comment]
In R side, there has been discussion to include PSIS and Pareto k diagnostics to the posterior package, to have more natural dependency for things which are not about cross-validation

**Comment by jgabry** [comment]
Thanks @bbbales2 and @avehtari. I just pushed more edits based on your suggestions. Ben, if you pull and regenerate the docs, does the doc page for `lp` look good to you now or did I miss anything?

**Comment by bbbales2** [comment]
Two super nitpicky changes but

> a posterior sample

Should be

> a posterior draw

Also change references to `lp` to be `lp__` and `lp_approx` to `lp_approx__`. Merge whenever.

Copying the text here if @avehtari wants a way to look at it without building the package.

```
Description
The $lp() method extracts lp__, the total log probability (target) accumulated in the model block of a Stan program. For variational inference the log density of the variational approximation to the posterior is also available via the $lp_approx() method.

See the Log Probability Increment vs. Sampling Statement section of the Stan Reference Manual for details on when normalizing constants are dropped from log probability calculations.

Details
lp is the unnormalized log density on Stan's unconstrained space. This will in general be different than the unnormalized model log density evaluated at a posterior sample (which is on the constrained space). lp is intended to diagnose sampling efficiency and evaluate approximations.

lp_approx is the log density of the variational approximation to lp (also on the unconstrained space). It is exposed in the variational method for performing the checks described in Yao et al. (2018) and implemented in the loo package.
```

**Comment by jgabry** [comment]
Thanks @bbbales2. Just fixed those and will merge now

**Comment by jgabry** [comment]
I just regenerated the online docs too, so the `lp` doc is now at http://mc-stan.org/cmdstanr/reference/fit-method-lp.html

**Pull request merged**
