### PR TITLE
Move rlang to suggests

### PR DESCRIPTION
**Pull request by jgabry**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

* Moves rlang package from Imports to Suggests (it's only required if `basename` isn't specified)
* renames the `suggest_package()` internal function to `require_suggested_package()`, which is why it actually does

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
**Columbia University**

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Review by rok-cesnovar — APPROVED** [review]

**Comment by jgabry** [comment]
I think the failure on Mac r-devel is unrelated to this PR (it's happening in other repos too due a failure to install R devel apparently).

**Comment by rok-cesnovar** [comment]
Indeed, CRAN seems to have issue with R-devel on Mac: https://mac.r-project.org/ lists some errors with R-devel. 

I set fail-fast to false in the meantime so we can see if tests pass elsewhere.

**Comment by jgabry** [comment]
Thanks!

**Comment by jgabry** [comment]
Ok looks like it's fine except for r-devel on Mac which we know is screwed up. So I think we can go ahead and merge. @rok-cesnovar Do you prefer if we keep fail-fast at false on master for now or set it back to true before merging? I'm fine either way, but if we leave it as false I will almost certainly forget to switch it back later when r-devel on Mac is working again ;)

**Comment by rok-cesnovar** [comment]
Lets keep it in false. Its not that bad if we forget :)

**Comment by jgabry** [comment]
Ok sounds good, merging now

**Pull request merged**
