### PR TITLE
Suppress some compilation messages in non-interactive R sessions

### LINKED ISSUE #429: Suppress the remaining messages in cmdstan_model() if quiet is TRUE?
I think it would be convenient if "Compiling Stan program..." and "Model executable is up to date!" were suppressed when `quiet` is `TRUE`.

``` r
library(cmdstanr)
#> This is cmdstanr version 0.2.2
#> - Online documentation and vignettes at mc-stan.org/cmdstanr
#> - CmdStan path set to: /Users/<CENSORED>/.cmdstanr/cmdstan-2.25.0
#> - Use set_cmdstan_path() to change the path
stan_program <- "
data {
  int<lower=0> N;
  int<lower=0,upper=1> y[N];
}
parameters {
  real<lower=0,upper=1> theta;
}
model {
  y ~ bernoulli(theta);
}
"
file <- write_stan_file(stan_program)

model <- cmdstan_model(file, quiet = TRUE)
#> Compiling Stan program...

model <- cmdstan_model(file, quiet = TRUE)
#> Model executable is up to date!
```

<sup>Created on 2021-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by wlandau**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Omit compilation messages "Compiling Stan program..." and "Model executable is up to date!" for non-interactive R sessions. Fixed #429.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 

Eli Lilly and Company

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by wlandau** [comment]
Unit tests tests passed on my local machine in both an interactive and non-interactive session. Looks like there are some issues installing MPI in the GitHub Actions workflows.

**Comment by rok-cesnovar** [comment]
@wlandau Thanks! Will take a look shortly. Seems there is an unrelated Ubuntu package installation issue, will restart tests until it goes away :)
```
Err:9 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libxnvctrl0 amd64 440.82-0ubuntu0.20.04.1
  404  Not Found [IP: 52.252.75.106 80]
```

**Comment by rok-cesnovar** [comment]
@wlandau please merge master in whenever you have the chance. The CI fix was pushed there.

**Review by rok-cesnovar — APPROVED** [review]
LGTM!

Thanks @wlandau!

**Pull request merged**
