### PR TITLE
Fix the use of seed for multi chain sampling

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Summary

Right now, cmdstanr sets different seeds for each of the cmdstan process call even if only one seed is given.
```
fit <- mod$sample(..., seed = 2)
```
will set seeds 2,3,4,5 for the 4 chains. This is not ok in the case where transformed uses any _rng functions as
that means that the 4 chains would not have the same data. Even if we set the same seed for all chains, the 
seed used in the rest of the model is actually the seed with a stride defined by the id. See https://github.com/stan-dev/stan/blob/develop/src/stan/services/util/create_rng.hpp#L27
So what we need to do is set the same seeds for all subprocesses.

Test model:
  
```stan
transformed data {
  int N = 100;
  vector[N] a;
  for (i in 1:N) {
    a[i] = uniform_rng(0, 1);
  }
}
parameters {
  real y;
}
model {
  y ~ std_normal();
}
generated quantities {
  vector[N] tdata = a;
  vector[N] gq;
  for (i in 1:N) {
    gq[i] = uniform_rng(0, 4);
  }
}
```

```R
mod <- cmdstan_model("model.stan")
fit <- mod$sample(iter_sampling = 1)
> fit$draws("tdata")
# A draws_array: 1 iterations, 4 chains, and 100 variables
, , variable = tdata[1]

chain
iteration    1    2    3   4
1 0.19 0.62 0.42 0.4

, , variable = tdata[2]

chain
iteration    1    2    3    4
1 0.74 0.67 0.49 0.31

, , variable = tdata[3]

chain
iteration    1    2    3     4
1 0.66 0.95 0.12 0.073

, , variable = tdata[4]

chain
iteration     1    2 3    4
1 0.011 0.82 1 0.45

# ... with 96 more variables

```

This PR fixes this so that these are the same across chains. A test was added to make sure chains actually have a different seed outside of data.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
Rok Češnovar

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
If someone wants explicitly different seed they can still set `seed = c(1,2,3,4)`. As far as I understand, this is required for something like SBC.

**Comment by rok-cesnovar** [comment]
This also matches the behavior of rstan and CmdStanPy.

**Comment by jgabry** [comment]
This makes sense. I think we should also update the doc for `seed` to mention what you said above about cmdstan using id to augment the single seed and that it's possible to specify a vector of seeds if the user wants to force different rng results in transformed data.

**Comment by rok-cesnovar** [comment]
Thanks @jgabry, added an attempt at the seed docs. Ready for a look.

**Review by jgabry — APPROVED** [review]
I made a few small edits to the `seed` doc, what do you think? If you're ok with the edits then I think this is ready to merge. 

Optionally, one other thing to consider: 

With this change `fit$metadata()$seed` will return a vector that looks like all chains used the same seed: 

```r
> fit <- cmdstanr_example(seed = 123)
> fit$metadata()$seed
[1] 123 123 123 123
```

Unless `seed` is specified as a vector with different elements should we change it so that `fit$metadata()$seed` just gives the single seed instead of the vector of replicated seeds? 

Not really a big deal, but perhaps worth considering.

**Comment by rok-cesnovar** [comment]
The doc changes look great! Thanks for the fixes!

> just gives the single seed instead of the vector of replicated seeds?

Good call. Will fix immediately.

**Pull request merged**
