### PR TITLE
FreeBSD support

### PR DESCRIPTION
**Pull request by tenomoto**
#### Submission Checklist

- [ ] Run unit tests
- [X] Declare copyright holder and agree to license (see below)

#### Summary

The make command on FreeBSD is BSD make.
`gmake` should be called instead of `make`.

* Add a function to detect FreeBSD.
* Modify `make_cmd()` to return `gmake` on FreeBSD.
* replace hard coded `make` to `make_cmd()`.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting
(this will be you or your assignee, such as a university or company):
Takeshi Enomoto

By submitting this pull request, the copyright holder is agreeing to
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by jgabry** [comment]
Thank you for the PR @tenomoto! @andrjohns @rok-cesnovar Any issues with adding this? 

The test failures are unrelated to these changes. I need to update one test after the latest release of the loo package.

**Comment by jgabry** [comment]
> I think the test failures (at least the ones I've checked) are unrelated to these changes: I need to [update one test](https://github.com/stan-dev/cmdstanr/pull/923) after the latest release of the loo package.

Just merged the fix into this branch so we'll see if everything passes now

**Comment by andrjohns** [comment]
@tenomoto Is there a reason to require GNU make on FreeBSD? MacOS uses BSD make with no issues

**Comment by andrjohns** [comment]
@tenomoto Before this can be merged, `cmdstan` itself should be able to run on FreeBSD, which does not appear to be the case. 

I just spun up a FreeBSD VM, and [the stanc3 transpiler](https://github.com/stan-dev/stanc3) does not have FreeBSD-compatible binaries. Additionally, the OS detection used in the Makefiles for the various submodules and libraries in `cmdstan` does not handle FreeBSD.

The contribution is very much appreciated, but we can't introduce codepaths which imply support that doesn't exist

**Comment by jgabry** [comment]
> I just spun up a FreeBSD VM, and [the stanc3 transpiler](https://github.com/stan-dev/stanc3) does not have FreeBSD-compatible binaries. Additionally, the OS detection used in the Makefiles for the various submodules and libraries in `cmdstan` does not handle FreeBSD.

Thanks for checking this @andrjohns

**Pull request closed without merging**
