### PR TITLE
Change the test example model

### LINKED ISSUE #35: Example model in cmdstan 2.21 changed
The example for 2.21 has changed. Its now a vectorized bernoulli (see https://github.com/stan-dev/cmdstan/issues/746) which means that the test-model fails if running with 2.21. 

The tests should work with the latest release since that is downloaded right? Do correct me if I am wrong.

A PR fix incoming.

This also raises the issue of having a upgrade_cmstan that deletes the existing cmdstan and installs the new version?

### PR DESCRIPTION
**Pull request by rok-cesnovar**
Fixes #35 

This PR changes the example model for the test resources & answers. For reasons behind this change see the issue.

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
@jgabry is there a way of restarting Travis tests. This one failed with 

```
downloading cmdstan-2.21.0.tar.gz from github
github download failed, curl exited with: 35
```

Which seems like a one time error non related to the PR.

**Comment by jgabry** [comment]
Yeah, if you go to https://travis-ci.org/stan-dev/cmdstanr/pull_requests (and log in to travis using your github account if necesssary) there should be a button to restart. I think you should have permissions to do that as a member of that stan-dev org, but if not (the restart button won't show up for you) let me know and I'll try to figure out how to allow you to do that.

**Comment by rok-cesnovar** [comment]
I am unable to restart, though I feel like I had the permissions of restarting for /stan, other repos I work with dont use Travis anymore so cant really say.

**Comment by jgabry** [comment]
Ok I just went ahead and restarted it, but let me see if I can also figure out how to get you permission to do that.

**Comment by jgabry** [comment]
Until I figure out how to set it up so you can restart builds from the website, the hacky way to do it would be just to make a commit that doesn't really change anything (e.g. add a single whitespace somewhere or some other inconsequential action). Any commit should start a new build.

**Comment by rok-cesnovar** [comment]
Yeah, dont bother with it too much. Hopefully there wont be much of these errors happening :)

**Pull request merged**
