### PR TITLE
Update model methods parameter naming and extract skeleton function

### PR DESCRIPTION
**Pull request by andrjohns**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Following the discussion in #720, the argument names to the model methods have been updated for consistency with the rest of the package (i.e., `pars` -> `variables`, and `upars` -> `unconstrained_variables`).

Returning the variable skeleton for structuring draws has also been separated out to its own method: `fit$variable_skeleton()`.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting
(this will be you or your assignee, such as a university or company):
Andrew Johnson

By submitting this pull request, the copyright holder is agreeing to
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by andrjohns** [comment]
@jgabry  and @rok-cesnovar does this cover all of the API changes that you were thinking of? (I've also updated the examples so that they should run sorry!).

I'll be adding the suggested `$unconstrain_draws()` function in the next PR

**Comment by jgabry** [comment]
> @jgabry and @rok-cesnovar does this cover all of the API changes that you were thinking of?

Yeah I think so, thanks!

**Comment by andrjohns** [comment]
Now added a fix and test for the zero-length containers handling from #723, so this is now ready for review (assuming tests pass!)

**Review by rok-cesnovar — APPROVED** [review]
Thanks!

**Pull request merged**
