### PR TITLE
Beta release

### LINKED ISSUE #253: Beta release schedule
@rok-cesnovar The only open issue in the beta release milestone is now #200 (Vignettes)! I think we probably have enough in the vignettes for the beta release (is there anything we obvious need that we don't have?), although I do think we should add those additional vignettes for the 1.0 release. What do you think? Should we move forward with the beta release? Especially given all the problems with RStan recently, unless we're waiting on something crucial, maybe we should go ahead?

@mitzimorris I think CmdStanPy technically is already in beta, right? If not in beta, how close are you to ready? If already in beta, then when we do CmdStanR's beta release I guess we can announce both?

### PR DESCRIPTION
**Pull request by jgabry**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Closes #253 

This PR contains the changes necessary for the beta release: 

* Update version number to `0.1.0`
* Fix any references to "pre-beta"
* Starts a NEWS.md file (standard way of doing release notes in R)
  - For the beta release the entry just says "Beta release" but going forward we'll list any changes 
* Regenerate the website files (this is responsible for most of the "changed files")

Anything I forgot? Once this is merged we should tag the beta release and announce it, so let's not rush this and make sure that this PR has everything needed before merging. 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
**Columbia University**

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
Great! Will take a look tomorrow.

**Comment by rok-cesnovar** [comment]
I only found one doc fix that needs to be done, but even that isn't related to the beta release. I can clean them up, but I am still a bit confused about regenerating the HTML and Rd files.

- In install.R we mention that install_cmdstan also installs the development version, which is not true:
```
#' @description The `install_cmdstan()` function attempts to download and
#'   install the latest release of
#'   [CmdStan](https://github.com/stan-dev/cmdstan/releases/latest) or a
#'   development version from a repository.
```

**Comment by jgabry** [comment]
Thanks, I just fixed the install_cmdstan doc and regenerated the pages.  

> I am still a bit confused about regenerating the HTML and Rd files.

Yeah this is a bit confusing. For a case like this where only one page needs to be changed, here's what I did: 

1. Edit the doc in the `install.R` file
2. Update the .Rd file by running `devtools::document()` (or `roxygen2::roxygenize()`) 
3. Update the single html file by running `pkgdown::build_reference(topics = "install_cmdstan")`

In other cases step 3 needs to be slightly modified. For example, for any doc pages that have examples of running cmdstan, we've wrapped them in `\dontrun{}`, which indicates to CRAN that it shouldn't try running those examples when checking the package (because CRAN won't have cmdstan installed). However, we do want to run and display the output from the examples on the website, so that requires adding the argument `run_dont_run = TRUE` when calling functions from `pkgdown`.

**Comment by rok-cesnovar** [comment]
Thanks for the fix and explanation. Have to bookmark this comment now :) This is good to go now I think.

**Comment by jgabry** [comment]
Should we go ahead and merge this and do the beta release? Or do you want to wait for #256? I'm ok either way, but I think it's probably ok for us to just go ahead and merge this and tag the beta release. Then we can merge #256 whenever we've settled the naming issue. Does that work for you? If so I can go ahead and merge this and tag the release (and I guess announce on discourse?)

**Comment by rok-cesnovar** [comment]
I think #256 is a minor thing and can definitely wait.

**Comment by jgabry** [comment]
I guess we could also wait for #257 to make sure everyone has fast compilation for the beta release. What do you think? Could be nice, but I'm fine either way.

**Comment by rok-cesnovar** [comment]
I will fix #256 tomorrow (need to replace names in the tests as well, but I am done for today). I think we can just roll with beta without that.

**Comment by jgabry** [comment]
Ok great. I'll go ahead and tag the beta release!

**Pull request merged**
