### PR TITLE
Add parse_metadata to read_cmdstan_csv

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Summary

@jgabry This is a draft because I want your input here if it's something you agree with at all, before I write tests and polish this.

Essentially, this adds the fastest way of reading the CSV with data.table. It avoids reading and parsing metadata and doing anything else except for repairing variable names. We don't even split sampler diagnostics or warmup/post warmup (we might be able to do this without a big penalty though - need to check).

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
Rok Češnovar

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)    
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
Ah, forgot to mention. With a 500MB CSV file, the difference is about 2x (8s vs 16s).

**Comment by jgabry** [comment]
I'm definitely open to this. Is the idea just to give people who have huge models an option to sacrifice having the full benefits of the fitted model objects in exchange for getting their posterior draws much faster?

**Comment by rok-cesnovar** [comment]
Yes, exactly that. I have seen a few cases of users writing their own wrappers that do this and figured we might as well provide a way to do this.

**Comment by jgabry** [comment]
Ok cool, sounds good to me.

**Comment by rok-cesnovar** [comment]
Closing for now. Still plan on working on this soon.

**Pull request closed without merging**
