### PR TITLE
Nicer compile error messages

### LINKED ISSUE #207: Cmdstanr not forwarding compile errors
I'm not sure if this is me or not, but the develop cmdstanr isn't forwarding me my error messages.

If I compile a model with a syntax error:
```
parameters {
  row_vector[3] a;
  vector[3] b;
}

model {
  matrix[1, 1] c = a * b;
}
```

With this R code:
```
library(cmdstanr)

model = cmdstan_model("/home/bbales2/tmp/test.stan")
```

I'm getting weird errors (instead of the syntax errors I expect):
```
> model = cmdstan_model("/home/bbales2/tmp/test.stan")
Compiling Stan program...
Error in processx::run(command = make_cmd(), args = c(tmp_exe, cpp_options_to_compile_flags(cpp_options),  : 
  System command error
```

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Fixes #207 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
Rok Češnovar, Univ. of Ljubljana

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
@jgabry  do we want to include a stan model that doesnt compile for tests purposes? If yes, I will also add a test here then.

**Comment by jgabry** [comment]
> @jgabry do we want to include a stan model that doesnt compile for tests purposes? If yes, I will also add a test here then.

Yeah good idea!

**Comment by rok-cesnovar** [comment]
Done here: https://github.com/stan-dev/cmdstanr/pull/208/commits/d94ec17cc3cc13a599227bfa2c8c5cee7a2fa091

We should fix this in cmdstan but not sure it's easy. The issue is make does not stop if stanc returns an error and tries to continue with the .hpp file. Which is not there.

**Comment by jgabry** [comment]
> Done here: [d94ec17](https://github.com/stan-dev/cmdstanr/commit/d94ec17cc3cc13a599227bfa2c8c5cee7a2fa091)

Awesome, thanks. 

> We should fix this in cmdstan but not sure it's easy. The issue is make does not stop if stanc returns an error and tries to continue with the .hpp file. Which is not there.

I see, that makes sense, thanks.

**Pull request merged**
