### PR TITLE
Generalize compiling

### LINKED ISSUE #120: Enable running pre-built models
This is a question to see how other see this feature. This is a use-case that would help maintaining some of the projects I am involved with, but I do not want to force it in cmdstanr if others dont see it as useful.

**Description:** 

Enable the users to run pre-build models using cmdstanr. This is useful for when you want to ship a pre-built Stan model as an executable to the end-user (for their OS) and enable them to easily use it via R. This is mainly so that they dont have to deal with any installation of compilers and toolchains if they are only interested in one specific model. Its probably not a really common use case.

Proposed use would be: 
`mod <- cmdstan_model(exe = "path/to/pre-built/exe/file)`
and the rest is then as usual.

### LINKED ISSUE #121: simplify/generalize model compilation options
**Is your feature request related to a problem? Please describe.**

CmdStanModel constructor and `compile` method take a series of named arguments for the CmdStan makefile variables, currently:

- arg `threads` for Makefile var `STAN_THREADS`
- arg `opencl` for stanc3 compiler arg `--use-opencl`
- args `opencl_device_id.` for Makefile vars `OPENCL_DEVICE_ID`
- ditto `opencl_platform_id`

We need to minimize dependencies between CmdStanX wrappers and the Stanc3 compiler and CmdStan makefiles.

**Describe the solution you'd like**

Implement a more general organization of user-facing compiler options instead of having many specific named options which will:

- Differentiate between arguments for options for `bin/stanc` vs. options to calls to `make` at the user-facing API.
- Provide getter/setter methods for compiler and makefile options.  These options should be  object-specific, therefore, don't rewrite user's `make/local` file.
- Check `bin/stanc` compiler options, because compiler throws an error on unrecognized options
- Pass `make` options into compiler unchecked
- disallow Stanc3 compiler debug flags - debugging the compiler is outside of the scope of the CmdStanX wrappers.

**Additional context**

We need an extensible solution that provides similar user-facing API for CmdStanPy and CmdStanR and future CmdStanX wrappers.  If the Stanc3 compiler introduces new arguments, then the CmdStanX wrappers need to change accordingly but otherwise, the CmdStanX wrappers should just work with new CmdStan releases.

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Fixes #121 and also fixes #120

Adds `cpp_options`, `stanc_options` and `model_name` to `$compile()`

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
Rok Češnovar

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
This is now ready for review.

**Comment by rok-cesnovar** [comment]
I refactored this again and I think this should be the way to go. Seemless for the user, not hacky and the least intrusive.

Cmdstanr helps keep "flagged" version of main.o: 
```
main_noflags.o
main_threads.o
main_opencl.o
...
```
based on supplied cpp_options, it moves the correct main_*.o to main.o. Same for model_header.hpp.gch if used (used with clang).

I made a test gist: https://gist.github.com/rok-cesnovar/7a5a11b89cb1759fd65cfa0b6cbe1848
It should produce something like:
```
[1] "First without flags"
Compiling Stan program...
Time difference of 51.15341 secs
[1] "second without flags"
Compiling Stan program...
Time difference of 8.325357 secs
[1] "first with threads"
Compiling Stan program...
Time difference of 48.44692 secs
[1] "second with threads"
Compiling Stan program...
Time difference of 7.581914 secs
[1] "third without flags"
Compiling Stan program...
Time difference of 7.606306 secs
[1] "third with threads"
Compiling Stan program...
Time difference of 8.220567 secs
```

**Comment by jgabry** [comment]
Thanks @rok-cesnovar! Looks like some tests are failing but otherwise looks OK to me.

**Comment by jgabry** [comment]
Actually I just noticed a few very minor things: 

* When compiling we're always printing the same message "Compiling Stan program..." regardless of whether we're also compiling `main.o`.  Can we add a message about also compiling `main.o` when that happens? That way the user isn't confused as to why it's taking longer. 

* The doc says that `include_paths`, `cpp_options`, and `stanc_options` are "character vectors", but the default for `cpp_options` and `stanc_options` is an empty `list()` instead of an empty character vector. Should these be specified as lists or vectors? Also the default of `include_paths` is `NULL`. Should these all have the same default? 

* Also on the topic of the new `cpp_options` and `stanc_options` arguments, can you provide a few examples demonstrating how to use those arguments?  These could go in the `@examples` section inside the `'dontrun{}` section that's already there.

**Comment by rok-cesnovar** [comment]
> * The doc says that `include_paths`, `cpp_options`, and `stanc_options` are "character vectors"

Ah yeah, copy paster error, options should be lists, while the paths should be character vectors.

Will add examples, was hoping to also make a vignette with the tutorial from @bbbales2 on the use of reduce_sum. But that comes later.

**Comment by jgabry** [comment]
> was hoping to also make a vignette with the tutorial from @bbbales2 on the use of reduce_sum. But that comes later.

That would be great! 

Also, does this PR break anything in that reduce_sum tutorial? I think @bbbales2 used the `threads = TRUE` argument, which is gone now right?

**Comment by bbbales2** [comment]
> I think @bbbales2 used the threads = TRUE argument, which is gone now right?

I take it when this gets merged I'll need to go update that?

**Comment by rok-cesnovar** [comment]
Yes, at that point we will do that with:

`mod <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE))`

**Comment by rok-cesnovar** [comment]
I can also make a PR to fix that once we merge this.

**Comment by bbbales2** [comment]
Cool beans. I made an issue to try to help myself remember: https://github.com/stan-dev/example-models/issues/175

**Comment by jgabry** [comment]
Thanks!

**Comment by rok-cesnovar** [comment]
I think this should be good now.

The vroom PR coming tomorrow hopefully will address #133 and #119 and then we  only need to address #7 and #136 for the beta. And maybe #20

**Comment by jgabry** [comment]
Thanks @rok-cesnovar! travis was failing due to a doc issue (all tests were passing), so I fixed that and I'll merge this now.

**Comment by rok-cesnovar** [comment]
Thanks!

**Pull request merged**
