### PR TITLE
add as_mcmc_list function

### PR DESCRIPTION
**Pull request by MatsuuraKentaro**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary
This `as_mcmc_list` function converts `CmdStanMCMC` object to `mcmc.list` object in the `coda` package. It is only a data conversion function, and it facilitates the transition to Stan for BUGS and JAGS users who are used to `mcmc.list`.

#### Copyright and Licensing
Please list the copyright holder for the work you are submitting
(this will be you or your assignee, such as a university or company):
Kentaro Matsuura

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by jgabry** [comment]
Thanks @MatsuuraKentaro, this looks good! I'm going to make a few small edits and then I'll go ahead and merge this. 

Also, I'm debating whether we should call this `as_mcmc_list` or `as_mcmc.list`. I prefer the underscores (`_`) but I still want to use the name of the actual class we're converting to, which is called `mcmc.list` in coda.  So maybe I'll go with `as_mcmc.list` even though it's a bit weird. 

And I'll also add an item to the NEWS.md file that mentions this and that you contributed it. Whenever we do the next official release of CmdStanR it will get included in the [News](https://mc-stan.org/cmdstanr/news/index.html) section of the CmdStanR website.

**Comment by jgabry** [comment]
Ok, I made a few small edits and added a few tests. I also added a comment in the documentation mentioning that this will be helpful for users of JAGS/BUGS who are familiar with coda, but I also mentioned that we do prefer the diagnostics in the posterior package and the plots in bayesplot. I mentioned that because, for example, the R-hat and effective sample size calculations in posterior use more recent (and we think improved) algorithms than the ones in coda, and bayesplot provides some HMC/NUTS specific plots that aren't available in coda but are important for Stan. But we don't want to force anyone to use bayesplot or posterior so I'm happy to have this function to make it easier to use coda for anyone who prefers that. 

Now let's just let the unit tests and checks run and if everything passes we can merge it. 

Thanks again @MatsuuraKentaro!

**Comment by MatsuuraKentaro** [comment]
Thank you very much for the minor changes, documents and tests. That's fine.

**Review by jgabry — APPROVED** [review]
Ok all the checks are passing so I'm going to merge. Thanks again @MatsuuraKentaro

**Pull request merged**
