### PR TITLE
RTools42 support

### LINKED ISSUE #637: Windows & RTools 4.2
R 4.2 and thus the switch to RTools 4.2 as opposed to 4.0 is coming shortly. We need to make sure everything still works with that setup.

I plan on looking at that this weekend at the latest.

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Closes #637 

Will post the final summary and reasons behind the fixes once we can confirm this is it - I am 90% certain that it is, but want a few others to test as well.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
Rok Češnovar

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)    
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
TODO: 
- [ ] get some additional confirmation this is good for R 4.2 on Windows
- [ ] test that it works with Github Actions
- [ ] do the same processx `env` trick for Rtools 4.0 (avoid writing to user's .Renviron)
- [ ] bump minor version

**Comment by rok-cesnovar** [comment]
Everything should now be working for R 4.2 users on Windows. I confirmed this on Github Actions as well as some additional systems I can access. @tjmahr has confirmed that it works (with some warnings/error) in the issue. I was able to replicate his issues and fixed them. 

@jgabry do you mind if I merge this assuming tests pass? I would like to make a Stan blog post warning users about what is going on. I bumped the package version as well.

The only really big change is the new `withr` dependency - each call to processx is now wrapped into a `withr()` call that makes sure all the right paths are set up. We previously did this by manipulating the PATH with `Sys.setenv()` and writing to .renviron in the toolchain check. I think this is cleaner and safer now. Do let me know if you disagree.

**Comment by rok-cesnovar** [comment]
I would like to merge this soon because the 4.2 release is now officially out.

**Comment by rok-cesnovar** [comment]
@jgabry do you mind if I go ahead and merge this PR with the bumped release version? R 4.2 has been released and I want to put out a blog post with the news on how to address Stan+Windows+R4.2 issues.

I can rebuild the website once the PR is merged.

**Comment by jgabry** [comment]
Sorry for the delay, I've been away. Fine to merge if you think it's ready!

**Comment by rok-cesnovar** [comment]
Great, can you let me know what you run to rebuild the website?

**Comment by jgabry** [comment]
To rebuild the whole site: 

```r
withr::with_envvar(c("NOT_CRAN" = "true"), pkgdown::build_site(run_dont_run = TRUE, seed = 1234))
```

Do you want to do add an entry to the Releases page too? https://github.com/stan-dev/cmdstanr/releases

Thanks for fixing the windows issues!

**Comment by jgabry** [comment]
I have some time now so I can update the NEWS and add to the releases page

**Comment by rok-cesnovar** [comment]
Thanks!

**Pull request merged**
