### PR TITLE
replace \ with function

### PR DESCRIPTION
**Pull request by jsocolar**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

This enables cmdstanr to install on R versions <= 4.0.  I've tested on 4.0, but not explicitly on earlier versions. Can close https://github.com/stan-dev/cmdstanr/issues/788

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting
(this will be you or your assignee, such as a university or company):
**NCX, 2443 Fillmore St. #380-1418, San Francisco, CA 94115**

By submitting this pull request, the copyright holder is agreeing to
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Review by rok-cesnovar — APPROVED** [review]
Thanks a ton! Will merge when/if the tests pass.

**Comment by jsocolar** [comment]
Looks like this is finally passing on R 3.6.  Couple of things:

- CI won't pass on R 3.5 because RcppEigen apparently depends >= 3.6.  Since RcppEigen is just in suggests, I assume it's fine to leave the depends at R 3.5. On the other hand it might be cleaner to bump to 3.6. I've not made any change.
- R added the `simplify` argument to `apply` in 4.1, and I've coded around that in [2a002e5](https://github.com/stan-dev/cmdstanr/pull/789/commits/2a002e505b0a3a9992c9302c4b8b8cb868851509).  However, I haven't actually stepped through that function and looked at the behavior of the workaround; I'm just trusting the test harness to catch problems.  Just want to flag for you that you might want to double check that change.

**Comment by rok-cesnovar** [comment]
We can leave it at 3.5 for now, given that rcppeigen is not mandatory. The apply change looks fine to me, thanks for highlighting it!

**Comment by jgabry** [comment]
Thanks Jacob and Rok!

**Pull request merged**
