### PR TITLE
Superclass to simplify shared fitted model methods

### LINKED ISSUE #83: R6 CmdStanFit superclass
To handle and simplify the methods common to all the fitted model classes I think we should introduce a superclass CmdStanFit, which is easy with R6:

* CmdStanMCMC, CmdStanVB, CmdStanMLE, etc., all inherit from the superclass CmdStanFit and only need to implement methods not implemented for the superclass
* CmdStanFit has the methods shared between the different fitted model classes (e.g. `$save_output_files()`)
* avoids repeated calls to `$set()` to set common methods and reduced code in other ways too

This has zero user-facing consequences since they only see the CmdStanMCMC (MLE, etc) object and don’t interact with CmdStanFit directly. 

I have a preliminary implementation up on the `CmdStanFit-superclass` branch.

### PR DESCRIPTION
**Pull request by jgabry**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Closes #83 (when finished). 

To handle and simplify the methods common to all the fitted model classes I think we should introduce a superclass `CmdStanFit`, which is easy to do with R6 inheritance and will help simplify some of the R code for sharing methods between the fitted model objects. **This has zero user-facing consequences** since the user only sees the `CmdStanMCMC` (MLE, etc) object and wouldn't interact with the `CmdStanFit` class directly. 

The changes currently included in this PR:

* `CmdStanFit` has the methods shared between the different fitted model classes (e.g. `$save_output_files()`)

* `CmdStanMCMC`, `CmdStanVB`, `CmdStanMLE`, etc., all `inherit` from the superclass `CmdStanFit` and only need to implement class-specific methods not implemented for the superclass

NOTE: This branches off of the in progress PR #79 (made it a bit easier to work with that branch). The only changes that need to be reviewed separately for this PR are the ones `R/fit.R` (all the other files like `R/run.R` and the test files are reviewed over at #79).  

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
**Columbia University**

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by jgabry** [comment]
@rok-cesnovar I think this is ready for review. 

In addition to the changes mentioned above I did the following:

* added a `testthat/teardown-remove.files.R` file, which removes everything from `testthat/resources/stan` that isn't a Stan program. Files with prefix "teardown" get run after all the test files finish, so we don't need to remove files created by `$compile()` in each test file now. 

* split up `testthat/test-fit.R` into separate files: 
   * test-fit-shared: tests methods shared by all CmdStanFit objects
   * test-fit-mcmc: tests unique to CmdStanMCMC
   * test-fit-mle: tests unique to CmdStanMLE
   * test-fit-vb: tests unique to CmdStanVB

**Comment by rok-cesnovar** [comment]
Great! I will have a look tomorrow. Fighting with appveyor has burned all my focus for today :)

**Comment by jgabry** [comment]
@rok-cesnovar No rush! And sorry again the appveyor thing has been so tedious. (We can also come back to that later before releasing if you need a break from it!)

**Comment by rok-cesnovar** [comment]
It has now become personal haha :) I am intrigued as to what is up here so I think I am not going to give up just yet.

**Comment by jgabry** [comment]
I added a few more tests and one had a typo so it caused the CI to fail. Should be fixed and all set now.

**Pull request merged**
