### PR TITLE
Print method

### LINKED ISSUE #27: Decide what print should do for fitted model objects
What should the `$print()` methods show for the different fitted model objects? Is it different than `$summary()` These include CmdStanMCMC, CmdStanMLE, and CmdStanVB objects, and eventually also CmdStanGQ objects once implemented.

### PR DESCRIPTION
**Pull request by jgabry**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Closes #27 

* Implements a `$print()` method for fitted model objects. Based on a suggestion from Andrew (who doesn't like the way tibbles are printed), the print method is the same as `$summary()` but drops all the weird tibble formatting.

* In the process I also added a `variables` argument to `$summary()` 

To see the difference between print and summary do: 

```r
fit <- cmdstanr_example("logistic")
fit$summary(variables = "beta") # prints with tibble formatting
fit$print(variables = "beta") # prints with regular formatting
```

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
**Columbia University**

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by bbbales2** [comment]
> Based on a suggestion from Andrew (who doesn't like the way tibbles are printed), the print method is the same as $summary() but drops all the weird tibble formatting.

Can we start referring to base r as boomeR? Or boomR? Am I stealing that joke from somewhere?

I guess package-wise, it's weird we have two differently named functions that are basically the same as each other but with either `%>% as_tibble()` at the end or `as.data.frame(...)` wrapped around the output.

I think we should try to reduce this to one function.

I guess:

1. What did Andrew not like about the tidy output? @andrewgelman

2. What about just making the current summary print?

**Comment by jgabry** [comment]
> Can we start referring to base r as boomeR? Or boomR? Am I stealing that joke from somewhere?

Haha nice. First I've seen it, but I'm not on twitter...

For (1) the objection was that it has all this weird underlining and colors and irregular rounding. Personally, I agree with Andrew on this. I don't particularly like the standard tibble formatting either.  

For (2) yeah we could just remove the tibble formatting from `summary`. I'd be ok with that. If we do that then we're back to "What should `print()` do?".

**Comment by bbbales2** [comment]
> the objection was that it has all this weird underlining and colors

Hmm, I like colors everywhere, and so I guess this never bothered me and I never looked closely into what stuff meant.

But let's go ahead and do that. Here's a screenshot of the two outputs:

image

Things I would like to keep:
1. The output clearly indicates it is a tibble, so I know my options. I also like knowing how many rows/columns.

2. The tibble only prints 10 lines of output by default

Things that I'm not gonna complain if they come or go:
1. Types under the names, though someone used to tibbles might expect this.

2. Row numbers

Things I'm happy to get rid of
1. Red for negative numbers (apparently this is an option: https://pillar.r-lib.org/reference/pillar-package.html#package-options -- can we selectively do this?)

2. Underlining. Apparently every three digits gets underlined. I don't think this matters so much for the numbers we're printing.

> and irregular rounding

As far as the rounding, I think the rounding in the tibble output is better. It's giving you three significant digits, and you can do whatever with those digits.

It looks like the other thing is just printing up to a fixed decimal point, which will work nicely if all your parameters are like `[0.1, 10.0]`, but won't be great otherwise.

> "What should print() do?"

Just make `print` do the same thing as `summary` except force a print (`a = fit$print()` wouldn't be silent).

**Comment by bbbales2** [comment]
Also it looks like there's something wrong with the output formats of the print.

If I print with lots of digits I get:

```
> fit$print(digits = 10)
                     mean        median           sd          mad             q5             q95 rhat ess_bulk ess_tail
lp__      -987.8658980000 -9.876035e+02 6.4759790730 6.3166173000 -9.9907480e+02 -977.7508000000    1      965     1806
brk[1,1]     0.8998992317  9.192005e-01 0.0832914069 0.0765614640  7.3609530e-01    0.9938260000    1     4226     1684
brk[2,1]     0.8222655320  8.378260e-01 0.1124107391 0.1144834068  6.1690895e-01    0.9761987500    1     3788     1719
brk[3,1]     0.9105493460  9.292880e-01 0.0747563166 0.0673619310  7.6165960e-01    0.9938371500    1     3044     1285
brk[4,1]     0.8257124583  8.434860e-01 0.1127632020 0.1134122283  6.2016775e-01    0.9771512500    0     3471     1629
```

The tibble is:
```
> fit$summary()
# A tibble: 122 x 10
   variable         mean       median         sd        mad           q5          q95      rhat  ess_bulk ess_tail
   <chr>           <dbl>        <dbl>      <dbl>      <dbl>        <dbl>        <dbl>     <dbl>     <dbl>    <dbl>
 1 lp__     -987.8659    -987.6035    6.475979   6.316617   -999.0748    -977.7508    1.003612   965.8364 1806.786
 2 brk[1,1]    0.8998992    0.9192005 0.08329141 0.07656146    0.7360953    0.993826  1.002609  4226.818  1684.245
 3 brk[2,1]    0.8222655    0.837826  0.1124107  0.1144834     0.6169090    0.9761988 1.000619  3788.966  1719.800
 4 brk[3,1]    0.9105493    0.929288  0.07475632 0.06736193    0.7616596    0.9938372 1.001611  3044.486  1285.784
 5 brk[4,1]    0.8257125    0.843486  0.1127632  0.1134122     0.6201678    0.9771512 0.9993417 3471.037  1629.688
```

I think the last columns are getting rounded to ints (and are being floor'd rather than rounded).

**Comment by bbbales2** [comment]
Hmm, I guess it's mildly annoying that the ESS has more than three significant digits.

**Comment by jgabry** [comment]
Ok, @bbbales2 had a chat about this and decided it's too complicated to satisfy all goals via one method. So we'll go with `$print()` and `$summary()`. But as requested by @bbbales2 I did modify the print method to only print the first 10 rows by default. Current output: 

```r
fit <- cmdstanr_example("schools_ncp")
fit$print()
```
```
     variable   mean median   sd  mad     q5    q95 rhat ess_bulk ess_tail
 lp__         -46.96 -46.65 2.53 2.38 -51.55 -43.44 1.00     1576     1984
 mu             6.55   6.52 4.25 4.16  -0.32  13.48 1.00     3118     2144
 tau            4.74   3.78 3.89 3.53   0.33  12.10 1.00     2006     1666
 theta_raw[1]   0.35   0.37 0.97 0.94  -1.27   1.90 1.00     3344     3131
 theta_raw[2]   0.04   0.04 0.91 0.91  -1.44   1.55 1.00     3833     3088
 theta_raw[3]  -0.13  -0.15 0.95 0.94  -1.64   1.44 1.00     3648     2785
 theta_raw[4]   0.02   0.02 0.92 0.91  -1.52   1.54 1.00     4141     2626
 theta_raw[5]  -0.27  -0.28 0.90 0.89  -1.75   1.24 1.00     3782     2988
 theta_raw[6]  -0.15  -0.14 0.93 0.92  -1.67   1.34 1.00     4167     2742
 theta_raw[7]   0.34   0.33 0.93 0.91  -1.22   1.88 1.00     3092     2727

 # showing 10 of 19 rows (change via 'max_rows' argument)
```

```r
fit <- cmdstanr_example("schools_ncp")
fit$print(max_rows = 50)
```
```
    variable   mean median   sd  mad     q5    q95 rhat ess_bulk ess_tail
 lp__         -46.96 -46.65 2.53 2.38 -51.55 -43.44 1.00     1576     1984
 mu             6.55   6.52 4.25 4.16  -0.32  13.48 1.00     3118     2144
 tau            4.74   3.78 3.89 3.53   0.33  12.10 1.00     2006     1666
 theta_raw[1]   0.35   0.37 0.97 0.94  -1.27   1.90 1.00     3344     3131
 theta_raw[2]   0.04   0.04 0.91 0.91  -1.44   1.55 1.00     3833     3088
 theta_raw[3]  -0.13  -0.15 0.95 0.94  -1.64   1.44 1.00     3648     2785
 theta_raw[4]   0.02   0.02 0.92 0.91  -1.52   1.54 1.00     4141     2626
 theta_raw[5]  -0.27  -0.28 0.90 0.89  -1.75   1.24 1.00     3782     2988
 theta_raw[6]  -0.15  -0.14 0.93 0.92  -1.67   1.34 1.00     4167     2742
 theta_raw[7]   0.34   0.33 0.93 0.91  -1.22   1.88 1.00     3092     2727
 theta_raw[8]   0.06   0.07 0.97 0.98  -1.53   1.60 1.00     4139     3062
 theta[1]       8.96   8.29 6.70 5.76  -0.61  21.10 1.00     3352     2957
 theta[2]       6.91   6.78 5.60 5.12  -1.96  16.07 1.00     4783     3109
 theta[3]       5.57   5.82 6.47 5.61  -5.64  15.32 1.00     3606     2229
 theta[4]       6.76   6.75 5.78 5.18  -2.88  15.84 1.00     4197     3287
 theta[5]       4.94   5.24 5.51 5.09  -4.56  13.57 1.00     3889     3318
 theta[6]       5.59   5.79 5.81 5.33  -4.31  14.49 1.00     4536     3296
 theta[7]       8.65   8.12 5.97 5.47  -0.11  19.53 1.00     4339     3289
 theta[8]       6.97   6.83 6.48 5.69  -3.20  17.68 1.00     4032     2639
```

@bbbales2 What do you think?

**Comment by bbbales2** [comment]
Beautiful!

**Comment by rok-cesnovar** [comment]
Nice!

**Comment by bbbales2** [comment]
Works as well. Do the docs show up as `print.X` somewhere?

**Comment by jgabry** [comment]
I had forgotten about that but if you pull my commit from a few seconds ago it should now come up via any of  `?print.CmdStanMCMC`, `?print.CmdStanMLE`, or `?print.CmdStanVB`

**Comment by bbbales2** [comment]
This all works. I'm happy with this. Merge away if Andrew is happy with what we settled on.

**Comment by jgabry** [comment]
Ok cool, thanks for helping sort this out! Let's see what Andrew says

**Comment by jgabry** [comment]
Andrew seemed ok with it (via email) so let's merge this. The check on windows-latest (oldrel) is failing with error "there is no package htmltools", which I think we can ignore for now.

**Comment by jgabry** [comment]
This will also bump the version to `0.0.0.9006`

**Pull request merged**
