### PR TITLE
clarify print vs summary in doc

### PR DESCRIPTION
**Pull request by jgabry**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Updates doc to explain the speed difference between the print and summary methods. This was brought up in #377.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
**Columbia University**

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Review by rok-cesnovar — APPROVED** [review]
Thank you!

**Comment by jgabry** [comment]
I'm going to go ahead and merge this doc change. I have no idea why codecov thinks the coverage will change because of this doc only PR but codecov can be weird sometimes.

**Comment by rok-cesnovar** [comment]
> I have no idea why codecov thinks the coverage will change because of this doc only PR but codecov can be weird sometimes.

We run two codecov tests (one Linux, one windows). The Linux one is faster and reports first. The windows one then sometimes updates the comment and sometimes does not :man_shrugging:

**Comment by jgabry** [comment]
Oh that makes sense, good point!

**Pull request merged**
