### PR TITLE
don't exclude vignettes on GHA (except opencl vignette)

### PR DESCRIPTION
**Pull request by jgabry**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

advances #590 

* Gets the vignettes running on GHA (except the opencl vignette). Currently in the GHA workflow file we're telling r cmd check to skip building the vignettes, but then we're not alerted to any errors when making changes to the vignettes. So it would be good to have r cmd check on GHA build the vignettes if possible. 

* Moves the OpenCL vignette to a subdirectory so that we can have it online but not on CRAN 

* Fixes a few other r cmd check NOTEs that weren't causing a failure but could be flagged by CRAN

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
**Columbia University**

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)    
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by jgabry** [comment]
This seems successful except for the profiling vignette. For some reason it can't find the stan file in the `profiling-files` subdirectory: 

https://github.com/stan-dev/cmdstanr/runs/4172425847?check_suite_focus=true#step:16:210

Not sure why.

**Comment by jgabry** [comment]
I think the problem is that at the time the vignette code is being evaluated the `profiling-files` directory is no longer available. This is because subdirectories of `vignettes` don't get installed. The reason there's no error when using other subdirectories like `children/settings-knitr.Rmd` in vignettes is that this is used before installation to assemble the final version of the vignette to be installed, whereas we're trying to use `profiling-files/profiling_bernoulli_logit.stan` _after_ installation. 

One solution to this is to get rid of `profiling-files` and use `write_stan_file()` to write the Stan files in the vignette. Testing this now.

**Comment by jgabry** [comment]
> One solution to this is to get rid of `profiling-files` and use `write_stan_file()` to write the Stan files in the vignette. Testing this now

Ok this works.

**Review by rok-cesnovar — APPROVED** [review]

**Comment by rok-cesnovar** [comment]
Thanks for cleaning these up!

**Pull request merged**
