### PR TITLE
Add check for inits named with square brackets

### PR DESCRIPTION
**Pull request by mike-lawrence**
Addresses #451 (& stan-dev/cmdstan#966)

#### Submission Checklist

- [X] Run unit tests
- [X] Declare copyright holder and agree to license (see below)

#### Summary

Please describe the purpose of the pull request. 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
Michael A. Lawrence

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by mike-lawrence** [comment]
Ah shoot, silly mistakes in both code and in my procedure for checking the tests passed before submitting this PR. Corrected now.

**Review by rok-cesnovar — APPROVED** [review]
Nice, one suggestion for the error text. But can also leave it and improve the text later.

**Comment by rok-cesnovar** [comment]
Thanks for fixing this! Also, can you add an entry to the NEWS.md.

**Comment by rok-cesnovar** [comment]
Great! Will merge once tests pass again.

**Pull request merged**
