### PR TITLE
Compatibility fixes for cmdstan 2.33+

### PR DESCRIPTION
**Pull request by jgabry**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Fixes old array syntax in some examples. 
I've been teaching a Stan workshop and noticed when showing the cmdstanr doc that we still use the old array syntax in a few places. 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting
(this will be you or your assignee, such as a university or company):
**Columbia University**

By submitting this pull request, the copyright holder is agreeing to
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by jgabry** [comment]
I think there’s something else in the deprecations vignette that’s causing an error but I don’t have time to check right now. Will come back to this later tonight or in the next few days.

**Comment by jgabry** [comment]
@rok-cesnovar @andrjohns Actually the Deprecations vignette is now just wrong because it's all about deprecation warnings but all the warnings it shows are now errors as of 2.33. So we need to decide what to do about that vignette. Do we want to rewrite it to be about fixing errors instead of warnings? Something else. Until we figure that out every cmdstanr PR will error during unit tests because this vignette won't run with 2.33

**Comment by jgabry** [comment]
> @rok-cesnovar @andrjohns Actually the Deprecations vignette is now just wrong because it's all about deprecation warnings but all the warnings it shows are now errors as of 2.33. So we need to decide what to do about that vignette. Do we want to rewrite it to be about fixing errors instead of warnings? Something else? Until we figure that out every cmdstanr PR will error during unit tests because this vignette won't run with 2.33

I pushed one commit yesterday that I thought would fix it (changing array syntax) but turns out all the other warnings are errors now too. So not sure what we want to do about that.

**Comment by rok-cesnovar** [comment]
I would remove it and make an issue to make a short vignette on how to use the auto-formatter to convert these models.

**Comment by jgabry** [comment]
That sounds good to me

**Comment by jgabry** [comment]
This is still failing after removing the vignette, apparently because 2.33 broke a few things in cmdstanr. E.g., `expose_functions` seems to be broken (see https://github.com/stan-dev/cmdstanr/issues/845). So I don't think I can get the tests to pass until we fix that.

**Comment by andrjohns** [comment]
I'm going to merge #847 into this PR/branch since the vignette deprecations are also causing the tests in that PR to fail.

Then we can make this PR a general 2.33-fixes PR if anything else pops up

**Comment by jgabry** [comment]
Sounds good, thanks @andrjohns!

**Comment by andrjohns** [comment]
@jgabry @rok-cesnovar this is passing and ready to have a look at. The only change that I'm not sure about is that reading estimates after a failed `$optimize()` run is [now erroring when it doesn't under 2.32](https://github.com/stan-dev/cmdstanr/pull/843/files#diff-303cceff7baae77f615bb2de2ea012fbec3469d62ef8eff96d456c03e7293216R56)

No idea why, or how important it is

**Review by rok-cesnovar — APPROVED** [review]
The changes look good. I dont know about the optimize(), will investigate whether this was a change in cmdstan, but I think we can merge the PR before that.

**Comment by jgabry** [comment]
Looks good to me too, thanks!

**Pull request merged**
