### PR TITLE
Global option for turning off warning for partial initial values

### LINKED ISSUE #912: Be able to silence warning about init values being set only for subset of parameters
**Is your feature request related to a problem? Please describe.**
I am integrating `cmdstanr` into a package that calls `model$sample`. Some of my parameters are being optionally defined as follows:

```stan
array[is_poisson==1 ? 0 : 1] real kappa;
```

and if `is_poisson==1` is `FALSE`, I would like not to have to supply initial values for these. But when I don't I get a warning:

> Init values were only set for a subset of parameters. 
> Missing init values for the following parameters:
> sigma

**Describe the solution you'd like**
I'd like to be able to silence the above warning.

**Describe alternatives you've considered**
I could supply some sort of null values for the parameters, but that feels a bit messy.

**Additional context**
The package I'm working on repeatedly calls `model$sample` so the above warning is emitted repeatedly, causing a messy collection of stuff being printed to the console.

### PR DESCRIPTION
**Pull request by jgabry**
closes #912

#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Adds a global option to turn off warning about partial initial value specification. When `options(cmdstanr_warn_inits=TRUE)` (the default) the warning message now looks like this, with a new line about disabling the warning: 

```
Init values were only set for a subset of parameters. 
Missing init values for the following parameters:
alpha, beta

To disable this message use options(cmdstanr_warn_inits = FALSE).
```

When `options(cmdstanr_warn_inits=FALSE)` there is now no message at all. 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting
(this will be you or your assignee, such as a university or company):
**Columbia University**

By submitting this pull request, the copyright holder is agreeing to
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by jgabry** [comment]
@ben18785 I think this should give you what you were asking for in #912. Do you want to test this out before we merge it?

**Comment by jgabry** [comment]
Looks like the Windows failures are due to issues in the `install_cmdstan` step when it tries to run `pacman`: 

```
Error in `processx::run("pacman", args = c("-Sy", install_pkgs, "--noconfirm"), …`:
16
! System command 'pacman' failed
```

 https://github.com/stan-dev/cmdstanr/actions/runs/7732239038/job/21081730518?pr=913#step:11:16

**Comment by ben18785** [comment]
Thanks very much @jgabry -- works perfectly as described above.

**Comment by jgabry** [comment]
> Thanks very much @jgabry -- works perfectly as described above.

Great, thanks for testing.

**Comment by jgabry** [comment]
> Looks like the Windows failures are due to issues in the `install_cmdstan` step when it tries to run `pacman`:
> 
> ```
> Error in `processx::run("pacman", args = c("-Sy", install_pkgs, "--noconfirm"), …`:
> 16
> ! System command 'pacman' failed
> ```
> 
> https://github.com/stan-dev/cmdstanr/actions/runs/7732239038/job/21081730518?pr=913#step:11:16

@rok-cesnovar Any idea if this Windows issue is something we need to fix or just some temporary issue that will resolve itself (as is often the case with GitHub actions)?

**Comment by jgabry** [comment]
> @rok-cesnovar Any idea if this Windows issue is something we need to fix or just some temporary issue that will resolve itself (as is often the case with GitHub actions)?

Looks like this paceman issue is affecting users too: https://twitter.com/fusaroli/status/1753094135513493693

**Comment by jgabry** [comment]
Finally got everything passing here. I think this is a small enough change I could just merge, but will leave open for a bit longer in case @rok-cesnovar or @andrjohns has any issue with this.

**Review by rok-cesnovar — APPROVED** [review]
Looks great!

**Comment by jgabry** [comment]
Ok cool will go ahead and merge

**Pull request merged**
