### PR TITLE
catch PCH errors with informative message feature

### LINKED ISSUE #321: error: PCH file uses an older PCH format that is no longer supported
**Describe the bug**
Using cmdstanr::cmdstan_model  compile model  faces the error: 
PCH file uses an older PCH format that is no longer supported

**Operating system**
Mac OS 10.15.7

**CmdStanR version number**
0.1.3

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Summary

Fixes #321 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
Rok Češnovar, Uni. of Ljubljana

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Review by jgabry — APPROVED** [review]
Thanks! In general I think `grepl(..., fixed=TRUE)` is nicer that `regexpr(..., fixed=TRUE) > 0`, but it doesn't really matter. And we already use the latter already in multiple places in the codebase, so no big deal.

**Comment by rok-cesnovar** [comment]
Didn know that one(grepl vs regepxr). Is it worth it to open an issue to unify?

**Comment by jgabry** [comment]
> Didn know that one(grepl vs regepxr). Is it worth it to open an issue to unify?

Yeah `grepl` returns T/F, so that's pretty useful. Definitely not a big deal, but could be nice to unify next time one of us is looking for an easy issue to close ;)

**Comment by jgabry** [comment]
Passing all checks so will merge now. I also opened #385 about the grepl vs regexpr.

**Pull request merged**
