### PR TITLE
Add dedicated hpp generation step for future cmdstan compatibility

### PR DESCRIPTION
**Pull request by andrjohns**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

As discovered in this [thread on the forum](https://discourse.mc-stan.org/t/cmdstanr-cmdstan-model-can-compile-model-but-fails-to-make-it-available-in-r-unless-already-compiled/32939), the next version of `cmdstan` will automatically delete the `.hpp` file during the `make` process. This causes R to error when we try to read it in for later use in the model-methods compilation.

This PR adds a separate step for generating and reading the hpp file into the Model object

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting
(this will be you or your assignee, such as a university or company):
Andrew Johnson

By submitting this pull request, the copyright holder is agreeing to
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by andrjohns** [comment]
Also a good reminder to set up the CI to test against cmdstan `develop` at some point

**Comment by WardBrian** [comment]
You can also update your make command to "make foo.hpp foo" and it should build both the executable and hpp (if you also need the .o you can list it there as well)

**Comment by andrjohns** [comment]
> You can also update your make command to "make foo.hpp foo" and it should build both the executable and hpp (if you also need the .o you can list it there as well)

Ah good call, that should be a bit cleaner, will do

**Comment by andrjohns** [comment]
> > You can also update your make command to "make foo.hpp foo" and it should build both the executable and hpp (if you also need the .o you can list it there as well)
> 
> Ah good call, that should be a bit cleaner, will do

Hmm it looks like `processx` package is causing some weird behaviour with this, and the `.hpp` file is getting deleted anyway, but the same thing doesn't happen through the CLI:

```
> mod <- cmdstan_model(write_stan_file(modfile), force_recompile = TRUE, quiet = FALSE)
Compiling Stan program...
Running make /var/folders/1d/rjvd0h_n0yq20j13h4gdfytw0000gn/T//RtmpakNfuk/model-19f7c4a9fa8.hpp \
  /var/folders/1d/rjvd0h_n0yq20j13h4gdfytw0000gn/T/RtmpakNfuk/model-19f7c4a9fa8 \
  "STANCFLAGS +=  --name='model_292e651ef3fa7c848ba97246a126a03b_model'"

--- Translating Stan model to C++ code ---
bin/stanc --name='model_292e651ef3fa7c848ba97246a126a03b_model' --o=/var/folders/1d/rjvd0h_n0yq20j13h4gdfytw0000gn/T//RtmpakNfuk/model-19f7c4a9fa8.hpp /var/folders/1d/rjvd0h_n0yq20j13h4gdfytw0000gn/T//RtmpakNfuk/model-19f7c4a9fa8.stan

--- Translating Stan model to C++ code ---
bin/stanc --name='model_292e651ef3fa7c848ba97246a126a03b_model' --o=/var/folders/1d/rjvd0h_n0yq20j13h4gdfytw0000gn/T/RtmpakNfuk/model-19f7c4a9fa8.hpp /var/folders/1d/rjvd0h_n0yq20j13h4gdfytw0000gn/T/RtmpakNfuk/model-19f7c4a9fa8.stan

--- Compiling, linking C++ code ---
clang++ -Wno-deprecated-declarations -ffp-contract=off -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -D_REENTRANT -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2020.3/include    -O3 -I src -I stan/src -I stan/lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.4.0 -I stan/lib/stan_math/lib/boost_1.78.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials    -DBOOST_DISABLE_ASSERTS          -c -include-pch stan/src/stan/model/model_header_15_0.hpp.gch -x c++ -o /var/folders/1d/rjvd0h_n0yq20j13h4gdfytw0000gn/T/RtmpakNfuk/model-19f7c4a9fa8.o /var/folders/1d/rjvd0h_n0yq20j13h4gdfytw0000gn/T/RtmpakNfuk/model-19f7c4a9fa8.hpp
clang++ -Wno-deprecated-declarations -ffp-contract=off -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -D_REENTRANT -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2020.3/include    -O3 -I src -I stan/src -I stan/lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.4.0 -I stan/lib/stan_math/lib/boost_1.78.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials    -DBOOST_DISABLE_ASSERTS               -Wl,-L,"/Users/andrew/.cmdstan/cmdstan-2.33.1/stan/lib/stan_math/lib/tbb" -Wl,-rpath,"/Users/andrew/.cmdstan/cmdstan-2.33.1/stan/lib/stan_math/lib/tbb"        /var/folders/1d/rjvd0h_n0yq20j13h4gdfytw0000gn/T/RtmpakNfuk/model-19f7c4a9fa8.o src/cmdstan/main.o       -Wl,-L,"/Users/andrew/.cmdstan/cmdstan-2.33.1/stan/lib/stan_math/lib/tbb" -Wl,-rpath,"/Users/andrew/.cmdstan/cmdstan-2.33.1/stan/lib/stan_math/lib/tbb"     stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_cvodes.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_idas.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_kinsol.a  stan/lib/stan_math/lib/tbb/libtbb.dylib stan/lib/stan_math/lib/tbb/libtbbmalloc.dylib stan/lib/stan_math/lib/tbb/libtbbmalloc_proxy.dylib -o /var/folders/1d/rjvd0h_n0yq20j13h4gdfytw0000gn/T/RtmpakNfuk/model-19f7c4a9fa8
ld: warning: duplicate -rpath '/Users/andrew/.cmdstan/cmdstan-2.33.1/stan/lib/stan_math/lib/tbb' ignored
ld: warning: duplicate -rpath '/Users/andrew/.cmdstan/cmdstan-2.33.1/stan/lib/stan_math/lib/tbb' ignored

rm -f /var/folders/1d/rjvd0h_n0yq20j13h4gdfytw0000gn/T/RtmpakNfuk/model-19f7c4a9fa8.o
rm /var/folders/1d/rjvd0h_n0yq20j13h4gdfytw0000gn/T/RtmpakNfuk/model-19f7c4a9fa8.hpp
```

Given that this indicates some flakiness with the `processx` call to `make`, I think it's best to leave the `.hpp` generation explicit like in the current changes

**Comment by rok-cesnovar** [comment]
Reviewing this later today, thanks for the heads up!

**Review by rok-cesnovar — APPROVED** [review]
Actually, had some downtime just now. This looks great to me!

**Pull request merged**
