### PR TITLE
Add force_recompile global option

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Summary

Adds a global force_recompile option (`cmdstanr_force_recompile`) which can be useful for packages that use cmdstanr as a dependecy. In case of any issues, recompiling models typically can fix them (obviously we would want to fix them, but this is the next best thing).

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
Rok Češnovar

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)    
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by jgabry** [comment]
Seems like a good idea. I think r cmd check is failing because of a warning related to the doc. You might just need to regenerate the Rd file and push it.

**Comment by rok-cesnovar** [comment]
Indeed :) Pushed.

**Comment by rok-cesnovar** [comment]
I guess this is good to go?

**Comment by jgabry** [comment]
Yeah I'll merge now

**Pull request merged**
