### PR TITLE
check if stan_opencl is TRUE rather than just not NULL

### PR DESCRIPTION
**Pull request by jgabry**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Fixes https://github.com/stan-dev/cmdstanr/issues/29#issuecomment-831651530

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
**Columbia University**

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by jgabry** [comment]
@rok-cesnovar question: do we also need to change these

https://github.com/stan-dev/cmdstanr/blob/98cad96e5bee284b4df492f7659865a995e2bd4a/R/model.R#L392-L400

to all check for TRUE?

**Comment by rok-cesnovar** [comment]
Yeah, good call!

**Comment by jgabry** [comment]
Ok done. ready for review

**Review by rok-cesnovar — APPROVED** [review]
Looks great. Thanks!

**Pull request merged**
