### PR TITLE
Add argument `output_dir`

### LINKED ISSUE #89: Add `output_dir` argument to `$sample()` and other fitting methods
Following CmdStanPy (https://github.com/stan-dev/cmdstanpy/issues/133#issuecomment-551942038), if the user knows in advance that they want to save the output csv files we could do that via an `output_dir` argument. They can always call `$save_output_files()` afterwards, but this would save that step if they know the want the files.

### PR DESCRIPTION
**Pull request by jgabry**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Closes #89

* Builds off of the branch for PR #84 so should be reviewed after #84 is merged (the diff for this PR currently looks bigger than it really is since this branch includes all the changes from that one) 

* Adds argument `output_dir` to `$sample()`, `$optimize()`, and `$variational()` methods to control where output and diagnostic csv files are written:
   - e.g., `mod$sample(data = stan_data, output_dir = PATH_TO_DIRECTORY)`
   - internally `output_dir` is handled by `CmdStanArgs`
   - defaults to temporary directory (so default behavior stays the same)
* Added new test file `tests/testthat/test-model-output_dir.R`
* Refactored `copy_temp_files` to separate out generating file names into a different function that can also be called by `$new_files()` method of `CmdStanArgs` object.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
**Columbia University**

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by jgabry** [comment]
> Looks good to me (and works)!

Excellent, thanks!

**Comment by bbbales2** [comment]
Is there any reason I didn't merge this? Was I waiting on tests or whatever? If there's no reason to wait, merge away.

**Comment by jgabry** [comment]
> Is there any reason I didn't merge this? Was I waiting on tests or whatever? If there's no reason to wait, merge away.

Fine by me to merge. @rok-cesnovar are you good with this? It probably doesn’t need a second thorough review if you trust @bbbales2 ;), but just want to make sure you’re ok with adding this output_dir argument.

**Comment by rok-cesnovar** [comment]
I skimmed through this after merging #84 and I am good with the changes. Didnt do a really thorough review but I completely trust @bbbales2. So merging :)

**Comment by jgabry** [comment]
Thanks!

**Pull request merged**
