### PR TITLE
Add "Repository" entry to keep {renv} happy

### PR DESCRIPTION
**Pull request by andrewheiss**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Add a repository entry to DESCRIPTION so that renv knows that this comes from a non-CRAN repository (addresses https://github.com/stan-dev/cmdstanr/issues/850)

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting
(this will be you or your assignee, such as a university or company):
**Andrew Heiss**

By submitting this pull request, the copyright holder is agreeing to
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by jgabry** [comment]
Great, thanks for the PR! 

@rok-cesnovar @andrjohns I can't think of any reason why this would cause any issues, and it would resolve a spurious warning from renv, so I think we should do it. But before I merge this, just wanted to check if you know of any reason why we shouldn't do it.

**Comment by rok-cesnovar** [comment]
All for it.

**Comment by jgabry** [comment]
Also, @andrewheiss don't worry about the failing unit tests. Those are presumably due to #843 and should get sorted out when that's merged.

**Comment by andrewheiss** [comment]
Ok good, I won't :) Everything tested fine on my local fork on macOS, but I haven't updated to 2.33 yet

**Comment by kevinushey** [comment]
I don't think you want to add it _directly_ to the source package here; it should only be added when the package is built, if the built package is going to be uploaded to the public repository.

Otherwise, tools that install this package from GitHub (e.g. `remotes::install_github()`) could get confused when installing directly from this repository.

**Comment by kevinushey** [comment]
Perhaps more succinctly: I think the binary packages that are built and published at https://github.com/stan-dev/r-packages should include `Repository: Stan` or something similar, and that should happen in some sort of pre-build step for the packages that are built and published there.

**Comment by andrewheiss** [comment]
Ahh that makes sense. In that case, disregard this PR @jgabry. The `Repository: Stan` line will need to be added somewhere else (maybe here? https://github.com/stan-dev/r-packages/blob/gh-pages/src/contrib/PACKAGES and maybe added to the other packages that are hosted at https://mc-stan.org/r-packages/ like rstan, rstanarm, and StanHeaders - idk how Stan's package building infrastructure works 😕)

**Pull request closed without merging**
