### PR TITLE
Add method for unconstraining all parameter draws

### PR DESCRIPTION
**Pull request by andrjohns**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

This PR adds the `$unconstrain_draws()` method, which returns all parameter draws on the unconstrained scale (as requested [in this comment](https://github.com/stan-dev/cmdstanr/issues/720#issuecomment-1323391563)).

The method returns a list of unconstrained parameter vectors (i.e., one per iteration) for each chain:
```r
> fit <- cmdstanr_example("logistic","sample")
Compiling Stan program...
 
> fit$init_model_methods()
Compiling additional model methods...

> unconstrained_draws <- fit$unconstrain_draws()

> str(unconstrained_draws, max.level = 1)
List of 4
 $ 1:List of 1000
 $ 2:List of 1000
 $ 3:List of 1000
 $ 4:List of 1000

# Unconstrained parameters from first three iterations of first chain
> head(unconstrained_draws[[1]],3)
[[1]]
[1]  0.371162 -0.394881 -0.654985  0.710900

[[2]]
[1]  0.4911350 -1.0099300  0.0109536  0.8098760

[[3]]
[1]  0.164200 -0.882001 -0.554675  0.782383

```

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting
(this will be you or your assignee, such as a university or company):
Andrew Johnson

By submitting this pull request, the copyright holder is agreeing to
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by andrjohns** [comment]
@n-kall and @singmann how does this interface/format for unconstraining all parameter draws work for your use-cases?

**Comment by n-kall** [comment]
This looks great!
For iwmm, the process is generally (starting with a model fit): 
1) unconstrain the draws from the model fit
2) perform some transformations on a matrix of unconstrained draws (see [here](https://github.com/topipa/iwmm/blob/main/R/moment_match.R#L44)) which may require constraining the draws to regenerate generated quantities (e.g. `log_lik`)
3) constrain the transformed unconstrained draws

So the suggested code would do step 1) nicely.  However, I think it could be useful to have an option to unconstrain a draws object that is not the one stored in the model fit (providing it fits the expected structure). For example if one wanted to do some preprocessing on the draws (e.g. thinning?) before unconstraining.

**Review by rok-cesnovar — APPROVED** [review]
This looks great to me! Will let you debate and decide whether to add anything additionally as @n-kall describes or merge this as is and potentially add additional features later on.

**Comment by andrjohns** [comment]
@n-kall I've updated the method to take either a character vector of paths to CSV files, or an existing draws object when unconstraining as well. Was there anything else that would be helpful when unconstraining draws?

For the changes/updates to the formatting of unconstrained parameter objects, I've also opened #730 for a bit more discussion

**Comment by n-kall** [comment]
Fantastic, I think this will be quite helpful in the long run.

> Was there anything else that would be helpful when unconstraining draws?

Apart from what you've now mentioned in #730, I can't think of other feature requests for unconstraining draws.

**Pull request merged**
