### PR TITLE
enable jacobian argument for optimization

### LINKED ISSUE #761: Enable jacobian flag for `optimize`
Introduced in CmdStan 2.32. Would just be an additional argument to the existing `optimize` method. Related to #760 because in order to get a sample `optimize` should be run with jacobian turned on.

### PR DESCRIPTION
**Pull request by jgabry**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Adds `jacobian` argument to `optimize` method. 
Closes #761 and paves the way for #760 (adding Laplace sample)

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting
(this will be you or your assignee, such as a university or company):
**Columbia University**

By submitting this pull request, the copyright holder is agreeing to
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by jgabry** [comment]
I think this is ready for review. I put both @rok-cesnovar and @andrjohns as reviewers but this probably only needs one of you, it's not too complicated.

**Comment by jgabry** [comment]
I'll work on  #760 next

**Review by andrjohns — APPROVED** [review]
LGTM, thanks!

**Comment by jgabry** [comment]
> LGTM, thanks!

Thanks for reviewing. Will merge now and continue working on the Laplace method in https://github.com/stan-dev/cmdstanr/pull/800

**Pull request merged**
